### PR TITLE
Removing Daniel Kester from OWI website

### PR DESCRIPTION
**Pull request by mwernimont**
@jkreft-usgs @ldecicco-USGS Daniel requested to be removed from the website, so I'm just doing as he wishes.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
with the new professional pages coming out, and the lose of the "OWI" brand....do we want to get rid of people all-together?

**Comment by mwernimont** [comment]
Do the new professional pages have contractors as well or just feds?

**Comment by ldecicco-USGS** [comment]
I have no idea

**Comment by mwernimont** [comment]
Well it'd be nice to keep the contractors involved for the moment, but we can always get rid of the people later if you guys decide it to be best

**Comment by jread-usgs** [comment]
We checked, and contractors apparently can't create a profile page. I'd like to keep our people page.

**Comment by ldecicco-USGS** [comment]
Petition USGS to allow contractors and/or switch this people page to OWI contractors?

The new professional page is much easier to add pubs, I don't want to maintain both.

For context, our highest viewed individual owi people page has 7 views. Pretty good odds that 1 of those views is the actual person copy/pasting a reference, and 3-4 others are people in our office.

All that being said...I only make this argument when there's some pressing reason to resist the inertia and actually change something on the current People's page. So, status quo = good, but if there becomes any work to maintaining this page, I'd vote to ax it.

**Comment by jkreft-usgs** [comment]
I would love to reduce this page to a list of people with links to profile pages. (maybe contractors just link to something else- linkedin or something- if they want a page)  It would also make hugo-ification of the rest of the OWI site trivial instead of kind of hard.

**Pull request merged**
